# -*- coding: utf-8 -*-
"""Pizza toppings product mix.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/109Y7jRE5KlOC99A5XTKaP7p5IXW-ftt6
"""

import pandas as pd
import numpy as np
import random

# Define a list of pizza toppings
pizza_toppings = [
    "Pepperoni", "Mushroom", "Onion", "Sausage", "Bacon",
    "Extra cheese", "Black olives", "Green peppers", "Pineapple",
    "Spinach", "Chicken", "Ham", "Jalapenos", "Artichoke hearts",
    "Feta cheese", "Sun-dried tomatoes", "Anchovies", "Broccoli"
]

# Number of data entries
num_entries = 10

# Column 1: Rank (in ascending order)
ranks = np.arange(1, num_entries + 1)

# Column 2: Pizza topping (randomly chosen)
# Ensure unique toppings if num_entries is less than or equal to the number of available toppings
if num_entries <= len(pizza_toppings):
    toppings = random.sample(pizza_toppings, num_entries)
else:
    toppings = [random.choice(pizza_toppings) for _ in range(num_entries)]

# Column 3: Cost (random float, formatted as currency)
costs = [f"${random.uniform(0.20, 1.50):.2f}" for _ in range(num_entries)]

# Create a DataFrame
data = pd.DataFrame({
    'Rank': ranks,
    'Pizza Topping': toppings,
    'Cost': costs
})

print(data)

import math
import numpy as np


num_rows = math.factorial(10)
max_rank = 10

# Generate random numbers for each column
column1 = np.random.randint(1, max_rank + 1, size=num_rows)
column2 = np.random.randint(1, max_rank + 1, size=num_rows)
column3 = np.random.randint(1, max_rank + 1, size=num_rows)

# Create the new DataFrame
new_data = pd.DataFrame({
    'Column 1': column1,
    'Column 2': column2,
    'Column 3': column3
})

print(f"Newly created DataFrame with {num_rows} random numbers:")
print(new_data)

# Perform the requested mathematical operations
new_data['Column2 - Column1'] = new_data['Column 2'] - new_data['Column 1']
new_data['Column3 - Column2'] = new_data['Column 3'] - new_data['Column 2']
new_data['Column3 - Column1'] = new_data['Column 3'] - new_data['Column 1']

print("DataFrame with new calculated columns:")
print(new_data.head())

# Drop rows where any of the specified columns are less than or equal to zero
initial_rows = len(new_data)
new_data = new_data[
    (new_data['Column2 - Column1'] > 0) &
    (new_data['Column3 - Column2'] > 0) &
    (new_data['Column3 - Column1'] > 0)
]

# Reset index if desired, but not strictly necessary for this operation
# new_data = new_data.reset_index(drop=True)

final_rows = len(new_data)
print(f"Dropped {initial_rows - final_rows} rows. Remaining rows: {final_rows}")
print("DataFrame after dropping rows:")
print(new_data.head())

pizza_info = data.copy()
# Convert cost to numeric for calculations
pizza_info['Numeric Cost'] = pizza_info['Cost'].replace({r'\$': ''}, regex=True).astype(float)
# Create a 'rank: topping' string column
pizza_info['Rank Topping String'] = pizza_info['Rank'].astype(str) + ': ' + pizza_info['Pizza Topping']

# Create mapping dictionaries
rank_to_topping_map = pizza_info.set_index('Rank')['Rank Topping String'].to_dict()
rank_to_cost_map = pizza_info.set_index('Rank')['Numeric Cost'].to_dict()

# Create the new DataFrame by copying relevant columns from new_data
summary_df = new_data[['Column 1', 'Column 2', 'Column 3']].copy()

# Apply the 'rank: topping' mapping to create new columns
summary_df['Rank: Topping 1'] = summary_df['Column 1'].map(rank_to_topping_map)
summary_df['Rank: Topping 2'] = summary_df['Column 2'].map(rank_to_topping_map)
summary_df['Rank: Topping 3'] = summary_df['Column 3'].map(rank_to_topping_map)

# Calculate the sum of individual costs for each row
summary_df['Total Topping Cost'] = summary_df['Column 1'].map(rank_to_cost_map) + \
                                   summary_df['Column 2'].map(rank_to_cost_map) + \
                                   summary_df['Column 3'].map(rank_to_cost_map)

print("Newly created summary DataFrame with pizza topping information and total cost:")
display(summary_df.head())

initial_summary_rows = len(summary_df)
summary_df_no_duplicates = summary_df.drop_duplicates(subset=['Column 1', 'Column 2', 'Column 3'])
final_summary_rows = len(summary_df_no_duplicates)

print(f"Removed {initial_summary_rows - final_summary_rows} duplicate rows from summary_df.")
print(f"Remaining rows in summary_df_no_duplicates: {final_summary_rows}")
print("Summary DataFrame after removing duplicates:")
display(summary_df_no_duplicates.head())

summary_df_no_duplicates = summary_df_no_duplicates.sort_values(by='Total Topping Cost', ascending=False)
print("Top 10 pizza topping combinations by total cost:")
display(summary_df_no_duplicates.head(10))