# -*- coding: utf-8 -*-
"""Python intro.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-3Tzq13rAg8_S8QOdax0pDI0atVJjubp

1. List, tuple, set dictionary

2. How do you encounter missing values: fillna, drop na,

3. Lambda function

quick, one-time tool for small task. any number of arguments but only one expression.

Eg: map, filter, sort

4. Numpy, Pandas, Matplotlib , Seaborn

5. Squares from 1 to 10 for all even numbers
"""

squares_of_evens = [num ** 2 for num in range(0, 11) if num % 2 == 0]
print(squares_of_evens)

6. Add append, pop sort in dataframe

"""First, let's create a simple DataFrame with some missing values to work with. We'll simulate a dataset with 50 records."""

import pandas as pd
import numpy as np

# Create a sample DataFrame with 50 records
data = {
    'ID': range(1, 51),
    'Name': [f'Person_{i}' for i in range(1, 51)],
    'Age': np.random.randint(20, 60, 50),
    'City': np.random.choice(['New York', 'Los Angeles', 'Chicago', 'Houston', 'Phoenix', np.nan], 50, p=[0.2, 0.2, 0.2, 0.2, 0.1, 0.1]),
    'Score': np.random.uniform(70, 100, 50)
}
df = pd.DataFrame(data)

# Introduce some more NaN values artificially for demonstration
df.loc[df.sample(frac=0.05).index, 'Age'] = np.nan
df.loc[df.sample(frac=0.05).index, 'Score'] = np.nan

print("Original DataFrame with some missing values:")
display(df.head())
print("\nMissing values count:")
display(df.isnull().sum())

"""### Handling Missing Values: `fillna`

The `fillna()` function is used to fill NaN (Not a Number) values with a specified value or method. Here, we'll fill missing 'Age' values with the mean age and 'City' values with 'Unknown'.
"""

# Create a copy to show fillna without altering the original df for subsequent steps
df_filled = df.copy()

# Fill missing 'Age' with the mean age
df_filled['Age'] = df_filled['Age'].fillna(df_filled['Age'].mean())

# Fill missing 'City' with 'Unknown'
df_filled['City'] = df_filled['City'].fillna('Unknown')

# Fill missing 'Score' with the median score
df_filled['Score'] = df_filled['Score'].fillna(df_filled['Score'].median())

print("DataFrame after using fillna():")
display(df_filled.head())
print("\nMissing values count after fillna():")
display(df_filled.isnull().sum())

"""### Handling Missing Values: `dropna`

The `dropna()` function is used to remove rows or columns containing NaN values. Here, we'll remove rows where *any* value is missing. Note that `df` still contains original NaNs for this demonstration.
"""

# Create a copy to show dropna
df_dropped = df.copy()

# Drop rows that have any missing values
df_dropped = df_dropped.dropna()

print("DataFrame after using dropna():")
display(df_dropped.head())
print("\nMissing values count after dropna():")
display(df_dropped.isnull().sum())

"""### Sorting Data: `sort_values`

The `sort_values()` function is used to sort a DataFrame by one or more columns. Let's sort the original DataFrame (before fillna/dropna) by 'Age' in ascending order.
"""

# Sort the original DataFrame by 'Age' in ascending order
df_sorted_age = df.sort_values(by='Age', ascending=True)

print("DataFrame sorted by Age (ascending):")
display(df_sorted_age.head())

# Sort by 'City' then 'Score' (descending Score)
df_sorted_city_score = df.sort_values(by=['City', 'Score'], ascending=[True, False])

print("\nDataFrame sorted by City (ascending) then Score (descending):")
display(df_sorted_city_score.head())

"""### Adding Values to the DataFrame

You can add new rows or columns to a DataFrame. Here's how to add a new column 'Status' and a new row.
"""

# Create a second sample DataFrame to merge with
# Let's assume this new DataFrame contains additional information for some IDs
data_B = {
    'ID': range(1, 51, 2), # Only for even IDs in the original df for demonstration
    'Department': np.random.choice(['HR', 'Engineering', 'Marketing', 'Sales'], len(range(1, 51, 2))),
    'Hire_Date': pd.to_datetime(pd.date_range('2020-01-01', periods=len(range(1, 51, 2)), freq='ME')) # Changed 'M' to 'ME'
}
df_B = pd.DataFrame(data_B)

print("Second DataFrame (df_B):")
display(df_B.head())

# Merge df_with_new_col with df_B on the 'ID' column
# Using a left merge to keep all records from df_with_new_col
df_merged = pd.merge(df_with_new_col, df_B, on='ID', how='left')

print("\nMerged DataFrame (df_merged):")
display(df_merged.head())
display(df_merged.tail())