# -*- coding: utf-8 -*-
"""Random Forest Decision Tree - California Housing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SvzCBAaW80aPyrJJ4lbN9zLKBjI6LrjJ

Python libraries
"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report, roc_curve, auc
import seaborn as sns
import matplotlib.pyplot as plt

"""Load sample data"""

df = pd.read_csv('/content/sample_data/california_housing_train.csv')
display(df.head())

"""### 1. DataFrame Information"""

print(df.info())

"""### 2. Descriptive Statistics of Numerical Columns"""

display(df.describe())

"""### 3. Handle Missing Values

First, let's check for any missing values.
"""

print(df.isnull().sum())

# It appears 'total_bedrooms' has some missing values. Let's impute them with the median.
# The median is often preferred over the mean for imputation when data might be skewed or contain outliers.
if 'total_bedrooms' in df.columns:
    # Check again if there are actually missing values before attempting imputation
    if df['total_bedrooms'].isnull().sum() > 0:
        median_bedrooms = df['total_bedrooms'].median()
        df['total_bedrooms'] = df['total_bedrooms'].fillna(median_bedrooms)
        print("\nMissing values in 'total_bedrooms' imputed with median.")
    else:
        print("\nNo missing values found in 'total_bedrooms', imputation skipped.")
    print(df.isnull().sum()) # Verify imputation

"""### 4. Identify Correlation

Let's visualize the correlation matrix to understand relationships between numerical features.
"""

plt.figure(figsize=(10, 8))
sns.heatmap(df.corr(), annot=True, cmap='coolwarm', fmt=".2f")
plt.title('Correlation Matrix of Housing Data')
plt.show()

"""### 6. Create X and y variables for ML Model

We'll separate the features (`X`) from the target variable (`y`), which in this case is `median_house_value`.
"""

# Define features (X) and target (y)
X = df.drop('median_house_value', axis=1)
y = df['median_house_value']

print("Shape of X:", X.shape)
print("Shape of y:", y.shape)

display(X.head())
display(y.head())

"""### 7. Split the Data into Training and Testing Sets

To evaluate our machine learning model effectively, we'll split the data into training and testing sets. The training set will be used to train the model, and the testing set will be used to assess its performance on unseen data. A common split ratio is 80% for training and 20% for testing.
"""

# Split the data into training and testing sets
# test_size=0.20 means 20% of the data will be used for testing
# random_state ensures reproducibility of the split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)

print("Shape of X_train:", X_train.shape)
print("Shape of X_test:", X_test.shape)
print("Shape of y_train:", y_train.shape)
print("Shape of y_test:", y_test.shape)

"""### 8. Feature Scaling

Feature scaling is a crucial preprocessing step, especially for algorithms that are sensitive to the magnitude of features (e.g., gradient descent-based algorithms, distance-based algorithms like K-Nearest Neighbors, or Support Vector Machines). We will use `StandardScaler` to transform the features such that they have a mean of 0 and a standard deviation of 1. It's important to fit the scaler *only* on the training data to prevent data leakage from the test set.
"""

# Initialize the StandardScaler
scaler = StandardScaler()

# Fit the scaler on the training data and transform both training and test data
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

print("Shape of X_train_scaled:", X_train_scaled.shape)
print("Shape of X_test_scaled:", X_test_scaled.shape)

# Display the first 5 rows of the scaled training features to show the transformation
print("\nFirst 5 rows of scaled X_train:")
display(pd.DataFrame(X_train_scaled, columns=X_train.columns).head())

"""### 9. Analyze Target Variable Distribution

Let's look at the normalized value counts of the target variable `y` to understand its distribution.
"""

print("Normalized value counts for y:")
display(y.value_counts(normalize=True))

"""### 10. Convert Target Variable to Binary Classification

Since the request is to convert the `median_house_value` into a class variable (0 or 1), we will define a threshold. A common and robust choice is to use the median value of `median_house_value` as the threshold. This will create two roughly balanced classes:

*   `0`: `median_house_value` is less than or equal to the median.
*   `1`: `median_house_value` is greater than the median.

This conversion will be applied to the original `y` variable, as well as its training and testing subsets (`y_train` and `y_test`).
"""

# Calculate the median of the original 'median_house_value'
median_house_value_threshold = y.median()
print(f"Median 'median_house_value' used as threshold: {median_house_value_threshold}")

# Convert y to a binary class variable
y_binary = (y > median_house_value_threshold).astype(int)
y_train_binary = (y_train > median_house_value_threshold).astype(int)
y_test_binary = (y_test > median_house_value_threshold).astype(int)

print("\nOriginal y head:\n")
display(y.head())
print("\nBinary y head:\n")
display(y_binary.head())

print("\nNormalized value counts for y_binary:")
display(y_binary.value_counts(normalize=True))

"""### 11. Train a Random Forest Classification Model

Now that the target variable has been converted to a binary format and the features have been scaled, the next step is to train a classification model. A Random Forest Classifier is chosen for its robustness and good performance on various datasets. We will initialize it with specific parameters to control its complexity and prevent overfitting.
"""

# Initialize the Random Forest Classifier with specified parameters
# n_estimators: The number of trees in the forest.
# max_depth: The maximum depth of the tree.
# min_samples_split: The minimum number of samples required to split an internal node.
# random_state: Controls the randomness of the bootstrapping of the samples and features.
rf_classifier = RandomForestClassifier(n_estimators=100, max_depth=6, min_samples_split=4, random_state=42)

# Train the classifier using the scaled training data and the binary training target
rf_classifier.fit(X_train_scaled, y_train_binary)

print("Random Forest Classifier trained successfully.")

"""### 12. Evaluate the Random Forest Classifier

After training the model, it's crucial to evaluate its performance on the test set. We will use several metrics to assess how well our Random Forest Classifier is performing on the binary classification task. These metrics include:

*   **Accuracy Score**: The proportion of correctly classified instances.
*   **Classification Report**: Provides a detailed breakdown of precision, recall, f1-score, and support for each class.
*   **Confusion Matrix**: A table showing the number of true positive, true negative, false positive, and false negative predictions.
*   **ROC Curve and AUC**: The Receiver Operating Characteristic curve and the Area Under the Curve, which illustrate the classifier's performance across all possible classification thresholds.
"""

# Make predictions on the scaled test data
y_pred = rf_classifier.predict(X_test_scaled)

# Predict probabilities for the positive class (1) for ROC curve
y_pred_proba = rf_classifier.predict_proba(X_test_scaled)[:, 1]

# Evaluate the model
print("\nAccuracy Score:")
print(f"{accuracy_score(y_test_binary, y_pred):.4f}")

print("\nClassification Report:")
print(classification_report(y_test_binary, y_pred))

print("\nConfusion Matrix:")
cm = confusion_matrix(y_test_binary, y_pred)
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', cbar=False,
            xticklabels=['Predicted 0', 'Predicted 1'],
            yticklabels=['Actual 0', 'Actual 1'])
plt.title('Confusion Matrix')
plt.xlabel('Predicted Label')
plt.ylabel('True Label')
plt.show()

# Calculate ROC curve and AUC
fpr, tpr, thresholds = roc_curve(y_test_binary, y_pred_proba)
roc_auc = auc(fpr, tpr)

print(f"\nAUC Score: {roc_auc:.4f}")

# Plot ROC curve
plt.figure(figsize=(8, 6))
plt.plot(fpr, tpr, color='darkorange', lw=2, label=f'ROC curve (area = {roc_auc:.2f})')
plt.plot([0, 1], [0, 1], color='navy', lw=2, linestyle='--')
plt.xlim([0.0, 1.0])
plt.ylim([0.0, 1.05])
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('Receiver Operating Characteristic (ROC) Curve')
plt.legend(loc='lower right')
plt.grid(True)
plt.show()

"""### 13. Perform Cross-Validation

Cross-validation is a technique to evaluate the machine learning models on a limited data sample. It helps in assessing the generalization ability of the model and provides a more reliable estimate of performance than a single train-test split. We will use 5-fold cross-validation on the training data.
"""

# Perform 5-fold cross-validation
cv_scores = cross_val_score(rf_classifier, X_train_scaled, y_train_binary, cv=5, scoring='accuracy')

print("Cross-validation scores:", cv_scores)
print(f"Mean cross-validation accuracy: {cv_scores.mean():.4f}")
print(f"Standard deviation of cross-validation accuracy: {cv_scores.std():.4f}")

"""### 14. Feature Importance Analysis

Understanding feature importance helps in interpreting the model and can provide insights into which variables are most influential in predicting the target. For tree-based models like Random Forest, we can extract feature importances directly from the trained model.
"""

# Get feature importances from the trained Random Forest Classifier
feature_importances = rf_classifier.feature_importances_

# Get the feature names from the original DataFrame X
feature_names = X.columns

# Create a DataFrame to store feature names and their importances
feature_importance_df = pd.DataFrame({'Feature': feature_names, 'Importance': feature_importances})

# Sort the DataFrame by importance in descending order
feature_importance_df = feature_importance_df.sort_values(by='Importance', ascending=False)

print("\nFeature Importances:")
display(feature_importance_df)

# Optionally, visualize feature importances
plt.figure(figsize=(12, 7))
sns.barplot(x='Importance', y='Feature', data=feature_importance_df)
plt.title('Feature Importances from Random Forest Classifier')
plt.xlabel('Importance')
plt.ylabel('Feature')
plt.grid(axis='x', linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()

