# -*- coding: utf-8 -*-
"""String manipulation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bMkZIUHSx97YKSEKGUL2kglf5ho1-cRv

# Palindromes
"""

def is_palindrome(word):
  """
  Checks if a given word is a palindrome.

  A palindrome is a word, phrase, number, or other sequence of characters
  which reads the same backward as forward.

  Args:
    word: The input string to check.

  Returns:
    True if the word is a palindrome, False otherwise.
  """
  # Normalize the word: convert to lowercase and remove non-alphanumeric characters
  processed_word = ''.join(char.lower() for char in word if char.isalnum())

  # Compare the processed word with its reverse
  return processed_word == processed_word[::-1]

# Test cases
word1 = "madam"
word2 = "A man, a plan, a canal: Panama"
word3 = "hello"
word4 = "Racecar"

print(f"'{word1}' is a palindrome: {is_palindrome(word1)}")
print(f"'{word2}' is a palindrome: {is_palindrome(word2)}")
print(f"'{word3}' is a palindrome: {is_palindrome(word3)}")
print(f"'{word4}' is a palindrome: {is_palindrome(word4)}")

"""# Duplicates"""

def find_duplicates(input_list):
  """
  Finds duplicate elements in a list.

  Args:
    input_list: A list of elements.

  Returns:
    A list of duplicate elements.
  """
  seen = set()
  duplicates = set()
  for item in input_list:
    if item in seen:
      duplicates.add(item)
    else:
      seen.add(item)
  return list(duplicates)

# Test cases
list1 = [1, 2, 3, 4, 2, 5, 3, 6]
list2 = ['apple', 'banana', 'orange', 'apple', 'grape']
list3 = [1, 2, 3, 4, 5]

print(f"Duplicates in {list1}: {find_duplicates(list1)}")
print(f"Duplicates in {list2}: {find_duplicates(list2)}")
print(f"Duplicates in {list3}: {find_duplicates(list3)}")

"""# Key-value swapping"""

def swap_key_values(input_dict):
  """
  Swaps keys and values in a dictionary.

  If multiple keys map to the same value, the last key encountered
  for that value will be retained in the swapped dictionary.

  Args:
    input_dict: The dictionary to perform key-value swapping on.

  Returns:
    A new dictionary with keys and values swapped.
  """
  swapped_dict = {value: key for key, value in input_dict.items()}
  return swapped_dict

# Test cases
dict1 = {'a': 1, 'b': 2, 'c': 3}
dict2 = {'apple': 'fruit', 'banana': 'fruit', 'carrot': 'vegetable'}
dict3 = {1: 'one', 2: 'two', 3: 'three'}

print(f"Original dict1: {dict1}")
print(f"Swapped dict1: {swap_key_values(dict1)}\n")

print(f"Original dict2: {dict2}")
print(f"Swapped dict2: {swap_key_values(dict2)}\n")

print(f"Original dict3: {dict3}")
print(f"Swapped dict3: {swap_key_values(dict3)}\n")

"""Scope:
1. Modify swap_key_values to handle multiple keys for the same value
2. Find duplicates using a list
3. Use set versus list and monitor performance for high volume operations

# Word frequency
"""

def word_frequency(string_list):
  """
  Calculates the frequency of each string in a list.

  Args:
    string_list: A list of strings.

  Returns:
    A dictionary where keys are strings and values are their frequencies.
  """
  frequency_dict = {}
  for s in string_list:
    frequency_dict[s] = frequency_dict.get(s, 0) + 1
  return frequency_dict

# Test cases
list1 = ["apple", "banana", "apple", "orange", "banana", "apple"]
list2 = ["cat", "dog", "cat", "mouse", "dog", "cat", "bird"]
list3 = ["one", "two", "three"]
list4 = []

print(f"Frequency of {list1}: {word_frequency(list1)}")
print(f"Frequency of {list2}: {word_frequency(list2)}")
print(f"Frequency of {list3}: {word_frequency(list3)}")
print(f"Frequency of {list4}: {word_frequency(list4)}")

"""# Word Cloud"""

# Step 1: Import necessary libraries
import pandas as pd
import re
import nltk
from nltk.corpus import stopwords
from sklearn.feature_extraction.text import TfidfVectorizer
from wordcloud import WordCloud
import matplotlib.pyplot as plt

# Download NLTK stop words if not already downloaded
try:
    stopwords.words('english')
except LookupError:
    nltk.download('stopwords')
    print("Downloaded NLTK 'stopwords'.")

print("Libraries imported and NLTK stopwords checked/downloaded.")

"""### Creating a Sample CSV File

Since no sample CSV was provided, I'll create a simple one with a 'text' column for demonstration purposes. This file will be saved as `sample_tokens.csv` in your Colab environment.
"""

# Step 2: Create a sample CSV file
data = {
    'text': [
        "This is a sample sentence with some filler words like um and uh. It also has numbers like 123 and symbols!!!",
        "Another example to test the removal of common stop words such as the, is, and a. This is a good test, you know?",
        "Python programming is great. Data science with pandas is super cool 2024. Like, totally.",
        "Regular expressions are powerful for text cleaning. It's kinda awesome. The quick brown fox jumps over the lazy dog.",
        "The quick brown fox jumps over the lazy dog. A quick test for duplicate sentences.",
        "Jupyter notebooks are often used for data analysis and visualization. It is quite useful, right?"
    ]
}

sample_df = pd.DataFrame(data)
sample_df.to_csv('sample_tokens.csv', index=False)

print("Sample 'sample_tokens.csv' created:")
print(sample_df.head())

"""### Loading the CSV and Defining the Cleaning Function

Now, I'll load the `sample_tokens.csv` into a DataFrame. Then, I'll define a `clean_text` function that will remove stop words, common filler words, punctuation, and numbers using regular expressions. This function will be applied to the 'text' column of the DataFrame.
"""

# Step 3: Load the CSV into a pandas DataFrame
df = pd.read_csv('sample_tokens.csv')
print("\nDataFrame loaded from 'sample_tokens.csv':")
print(df.head())

# Step 4: Define the text cleaning function
stop_words = set(stopwords.words('english'))
# Add some common filler words to the stop_words set
filler_words = {'um', 'uh', 'like', 'you know', 'kinda', 'right', 'totally', 'yeah', 'okay'}
stop_words.update(filler_words)

def clean_text(text):
  text = str(text).lower() # Convert to string and lowercase
  text = re.sub(r'[^a-z\s]', '', text) # Remove punctuation and numbers
  text = ' '.join([word for word in text.split() if word not in stop_words]) # Remove stop words
  text = re.sub(r'\s+', ' ', text).strip() # Remove extra spaces
  return text

# Step 5: Apply the cleaning function to the 'text' column
df['cleaned_text'] = df['text'].apply(clean_text)

print("\nDataFrame after cleaning:")
print(df[['text', 'cleaned_text']].head())

"""### Vectorization and Word Cloud Generation

Next, I'll vectorize the `cleaned_text` using `TfidfVectorizer`, which converts text into a matrix of TF-IDF features. Finally, I'll generate and display a word cloud from the vectorized text to visually represent the most frequent and important terms.
"""

# Step 6: Vectorize the cleaned text
# Using TF-IDF Vectorizer
tfidf_vectorizer = TfidfVectorizer(max_features=100) # Limit to top 100 features for word cloud clarity
tfidf_matrix = tfidf_vectorizer.fit_transform(df['cleaned_text'])

# To generate word cloud, we need a single string of all words or word frequencies
# For simplicity, let's join all cleaned text into a single string for the word cloud
all_cleaned_text = ' '.join(df['cleaned_text'])

# Step 7: Generate and display a word cloud
wordcloud = WordCloud(width=800, height=400, background_color='white').generate(all_cleaned_text)

plt.figure(figsize=(10, 5))
plt.imshow(wordcloud, interpolation='bilinear')
plt.axis('off')
plt.title('Word Cloud of Cleaned Tokens')
plt.show()

print("\nText vectorized and word cloud generated successfully!")

import collections

# Split the all_cleaned_text into words
words = all_cleaned_text.split()

# Calculate word frequencies
word_counts = collections.Counter(words)

# Get the top 10 most common words
top_ten_words = word_counts.most_common(10)

print("\nTop 10 most common words and their frequencies:")
for word, count in top_ten_words:
    print(f"'{word}': {count}")